# Generated by Django 4.2.1 on 2023-05-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sabor', models.CharField(max_length=50)),
                ('ingredientes', models.TextField(max_length=30)),
                ('instrucciones', models.TextField(max_length=30)),
                ('tiempo_preparacion', models.IntegerField()),
                ('dificultad', models.CharField(max_length=20)),
                ('num_porciones', models.IntegerField()),
            ],
        ),
    ]
